"""report.py - builds outputs/report.html from outputs/tracks.csv."""

import os
import pandas as pd

CSV = "outputs/tracks.csv"
OUT = "outputs/report.html"


def main():
    if not os.path.exists(CSV):
        print(f"[ERROR] {CSV} not found. Run python main.py first.")
        return
    df = pd.read_csv(CSV)
    if df.empty:
        print("[ERROR] No vehicles found in CSV. Try a lower --conf value, e.g. --conf 0.2")
        return

    summary = df.groupby("object_id").agg(
        vehicle_class=("vehicle_class", "first"),
        first_seen_s=("time_s", "min"),
        last_seen_s=("time_s", "max"),
        frames_seen=("frame", "count"),
        best_conf=("confidence", "max"),
    ).reset_index().sort_values("object_id")

    class_counts = summary["vehicle_class"].value_counts().to_dict()
    total = len(summary)
    total_detections = len(df)
    crossings_in = int((df["event"] == "IN").sum())
    crossings_out = int((df["event"] == "OUT").sum())
    duration_s = float(df["time_s"].max()) if len(df) else 0.0

    cards = []
    for _, r in summary.iterrows():
        tid = int(r["object_id"])
        crop = f"crops/vehicle_{tid}.jpg"
        img_tag = (f'<img src="{crop}" width="220" alt="Vehicle {tid}">'
                   if os.path.exists(os.path.join("outputs", crop))
                   else "<i>No image available for this vehicle.</i>")
        cards.append(f"""
        <div class="card">
          <h3>ID #{tid} &mdash; {r['vehicle_class'].capitalize()}</h3>
          {img_tag}
          <p>Visible: {r['first_seen_s']:.2f}s to {r['last_seen_s']:.2f}s<br>
          Detections: {int(r['frames_seen'])} frames<br>
          Plate number: Not included in this prototype</p>
        </div>""")

    html = f"""<html><head><meta charset="utf-8"><title>Traffic Tracking Prototype &mdash; Analysis Report</title>
    <style>
      body {{ font-family: Arial, sans-serif; margin: 30px; background: #f4f4f4; color: #222; }}
      .box {{ background: white; padding: 20px 24px; border-radius: 10px; margin-bottom: 20px; }}
      .card {{ background: white; padding: 15px; border-radius: 10px; margin: 10px;
               display: inline-block; width: 260px; vertical-align: top; }}
      table {{ border-collapse: collapse; margin-top: 10px; }} td, th {{ border: 1px solid #ccc; padding: 6px 12px; text-align: left; }}
      .muted {{ color: #666; font-size: 0.9em; }}
    </style></head><body>
    <h1>Traffic Tracking Prototype &mdash; Analysis Report</h1>
    <div class="box">
      <h2>Summary</h2>
      <p><b>Unique vehicles tracked:</b> {total} &nbsp;|&nbsp; <b>Total detections:</b> {total_detections}
      &nbsp;|&nbsp; <b>Video duration:</b> {duration_s:.1f}s</p>
      <table><tr><th>Vehicle type</th><th>Count</th></tr>
      {''.join(f'<tr><td>{k.capitalize()}</td><td>{v}</td></tr>' for k, v in class_counts.items())}
      </table>
      <p><b>Line crossings:</b> IN: {crossings_in} &nbsp;|&nbsp; OUT: {crossings_out}</p>
      <h3>Method</h3>
      <p>Vehicles were detected with YOLOv8n and tracked with ByteTrack. Each vehicle keeps one
      tracking ID across all frames in which it is visible. Tracking IDs are unique but not always
      sequential, because some IDs belong to filtered or briefly lost detections.</p>
    </div>
    <h2>Tracked vehicles</h2>
    {''.join(cards)}
    <div class="box">
      <p class="muted">Prototype scope: single recorded video, vehicle-type tracking only.
      Frame-level data is available in tracks.csv. Generated by the Traffic Tracking Prototype.</p>
    </div>
    </body></html>"""

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"[OK] Report written: {OUT}")


if __name__ == "__main__":
    main()
